name: Automatización de Datos

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas matplotlib numpy xlrd openpyxl pandas-datareader imf-reader

      - name: Run script
        run: python ejecutar_codigo.py

      - name: Configurar git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Mover CSV
        run: |
          mkdir -p "Automatización de Datos"
          mv *.csv "Automatización de Datos/" || echo "No hay archivos"

      - name: Guardar cambios
        run: |
          git add .
          git commit -m "Actualización automática de datos" || echo "No hay cambios para commitear"
          git push
